
service: dbOps

frameworkVersion: "=1.11.0"

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/meetzam-mobilehub-1569925313-UserProfile" 

    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/movie_table" 

    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/movie_history" 
      
    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/chatroom" 

    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/meetzam-mobilehub-1569925313-Conversation" 


functions:

  addDeviceARN:
    handler: addDeviceARN.handler
    name: addDeviceARN-${self:provider.stage}
    description: this function add deviceARN to userProfile table
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  updateTimeStamp:
    handler: updateTimeStamp.handler
    name: updateTimeStamp-${self:provider.stage}
    description: this function update timeStamp in chatroom table
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  deleteChatRoom:
    handler: deleteChatRoom.handler
    name: deleteChatRoom-${self:provider.stage}
    description: this function delete chatroom in chatroom table
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  getPotentialMatch:
    handler: getPotentialMatch.handler
    name: getPotentialMatch-${self:provider.stage}
    description: return potential match of a user based on the user's user_id
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  batchDeleteConversation:
    handler: batchDeleteConversation.handler
    name: batchDeleteConversation-${self:provider.stage}
    description: batch delete conversation
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  deleteContact:
    handler: deleteContact.handler
    name: deleteContact-${self:provider.stage}
    description: delete contact
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6
